# Generated by Django 3.1.2 on 2020-10-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        ('contacts', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='optional only pick if your sending the message to parent or pick all to send message to student, parent, and teacher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parenttalk', to='students.student'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='student',
            field=models.ForeignKey(blank=True, help_text='optional only pick if your sending the message to student, or pick all to send message to student, parent, and teacher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studenttalk', to='students.student'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='optional only pick if your sending the message to teacher or pick all to send message to student, parent, and teacher', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachertalk', to='teachers.teacher'),
        ),
    ]
