# Generated by Django 3.1.2 on 2020-10-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20201016_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
