# Generated by Django 3.1.2 on 2020-10-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactus_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='heading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
