# Generated by Django 3.1.2 on 2020-10-16 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        ('contacts', '0005_auto_20201016_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='student',
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studenttalk', to='students.student'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachertalk', to='teachers.teacher'),
        ),
    ]
