# Generated by Django 3.1.2 on 2020-10-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20201016_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='name',
            new_name='myname',
        ),
    ]
