# Generated by Django 3.1.2 on 2020-10-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        ('contacts', '0008_auto_20201016_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='myname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentname', to='students.student'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachertalk', to='teachers.teacher'),
        ),
    ]
