# Generated by Django 3.1.2 on 2020-10-17 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_auto_20201016_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('parent_pic', models.ImageField(blank=True, null=True, upload_to='parentpics/%Y/%m/%d/')),
                ('message', models.TextField(null=True)),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contactus', 'verbose_name_plural': 'contactus'},
        ),
    ]
