# Generated by Django 3.1.2 on 2020-10-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20201017_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_1',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
