# Generated by Django 3.1.2 on 2020-10-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0013_remove_testmonial_parent_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonial',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
