# Generated by Django 3.1.2 on 2020-10-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_testmonial_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmonial',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
