# Generated by Django 3.1.2 on 2020-10-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_auto_20201019_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmonial',
            name='email',
        ),
        migrations.RemoveField(
            model_name='testmonial',
            name='phone',
        ),
    ]
