# Generated by Django 3.1.2 on 2020-10-20 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='english_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='englishteacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='kiswahili_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kiswahiliteacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='mathematics_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mathematicsteacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guardian', to='parents.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='science_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scienceteacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='social_studies_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='socialstudiesteacher', to='teachers.teacher'),
        ),
    ]
