# Generated by Django 3.1.2 on 2020-10-20 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0002_auto_20201020_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent',
            new_name='parent_gurdian',
        ),
        migrations.AddField(
            model_name='student',
            name='parent_father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='father', to='parents.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mother', to='parents.parent'),
        ),
    ]
