# Generated by Django 3.1.2 on 2020-10-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20201020_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
