# Generated by Django 3.1.2 on 2020-10-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_is_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='parent_gurdian',
            new_name='parent_guardian',
        ),
    ]
