# Generated by Django 3.1.2 on 2020-10-20 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('parents', '0001_initial'),
        ('students', '0005_auto_20201020_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='english_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='englishteacher', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='kiswahili_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kiswahiliteacher', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mathematics_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mathematicsteacher', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='father', to='parents.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guardian', to='parents.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mother', to='parents.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='science_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scienceteacher', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_studies_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='socialstudiesteacher', to='teachers.teacher'),
        ),
    ]
