# Generated by Django 3.1.2 on 2020-10-20 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20201020_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_father',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_guardian',
        ),
    ]
