# Generated by Django 3.1.2 on 2020-10-20 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parent_is_published'),
        ('students', '0007_auto_20201020_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='father', to='parents.parent'),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='guardian', to='parents.parent'),
        ),
    ]
