# Generated by Django 3.1.2 on 2020-10-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parent_is_published'),
        ('students', '0008_auto_20201020_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='parents.parent'),
        ),
    ]
