# Generated by Django 3.1.2 on 2020-10-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_grade1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_grade2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_grade3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_grade4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_grade5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_grade6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_grade7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_grade8',
            field=models.BooleanField(default=False),
        ),
    ]
