# Generated by Django 3.1.2 on 2020-10-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice_board', '0003_auto_20201010_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='slug',
        ),
    ]
