# Generated by Django 3.1.2 on 2020-10-17 15:59

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('title_1', models.CharField(max_length=200, null=True)),
                ('statement_1', models.CharField(max_length=200, null=True)),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title_2', models.CharField(max_length=200, null=True)),
                ('statement_2', models.CharField(max_length=200, null=True)),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title_3', models.CharField(max_length=200, null=True)),
                ('statement_3', models.CharField(max_length=200, null=True)),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title_4', models.CharField(max_length=200, null=True)),
                ('statement_4', models.CharField(max_length=200, null=True)),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title_5', models.CharField(max_length=200, null=True)),
                ('statement_5', models.CharField(max_length=200, null=True)),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title_6', models.CharField(max_length=200, null=True)),
                ('statement_6', models.CharField(max_length=200, null=True)),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title_7', models.CharField(max_length=200, null=True)),
                ('statement_7', models.CharField(max_length=200, null=True)),
                ('photo_7', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title_8', models.CharField(max_length=200, null=True)),
                ('statement_8', models.CharField(max_length=200, null=True)),
                ('photo_8', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('title_9', models.CharField(max_length=200, null=True)),
                ('statement_9', models.CharField(max_length=200, null=True)),
                ('photo_9', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('reload', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
