# Generated by Django 3.1.2 on 2020-10-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='reload',
            new_name='date_posted',
        ),
    ]
