# Generated by Django 3.1.2 on 2020-10-17 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200, null=True)),
                ('title2', models.CharField(max_length=200, null=True)),
                ('title3', models.CharField(max_length=200, null=True)),
                ('title4', models.CharField(max_length=200, null=True)),
                ('subtitle1', models.CharField(max_length=200, null=True)),
                ('subtitle2', models.CharField(max_length=200, null=True)),
                ('subtitle3', models.CharField(max_length=200, null=True)),
                ('subtitle4', models.CharField(max_length=200, null=True)),
                ('statement1', models.CharField(max_length=50, null=True)),
                ('statement2', models.CharField(max_length=50, null=True)),
                ('statement3', models.CharField(max_length=50, null=True)),
                ('statement4', models.CharField(max_length=50, null=True)),
                ('icon1', models.CharField(max_length=200, null=True)),
                ('icon2', models.CharField(max_length=200, null=True)),
                ('icon3', models.CharField(max_length=200, null=True)),
                ('icon4', models.CharField(max_length=200, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('service_statement', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Heading',
                'verbose_name_plural': 'Heading',
                'ordering': ['date_posted'],
            },
        ),
    ]
