# Generated by Django 3.1.2 on 2020-10-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_heading',
        ),
    ]
