# Generated by Django 3.1.2 on 2020-10-06 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(help_text='You must re enter the class name using dashes e.g class 7 west = class-7-west on the slug field', max_length=250, null=True, unique_for_date='date_posted')),
                ('class_teacher', models.CharField(max_length=100, null=True)),
                ('class_monitor', models.CharField(blank=True, max_length=200, null=True)),
                ('class_prefect', models.CharField(blank=True, max_length=200, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('is_mvp', models.BooleanField(default=False, help_text='click this if this is pp1, pp2, grade_1, grade_2, grade_3')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='students_joined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
