# Generated by Django 3.1.2 on 2020-10-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0003_remove_grade_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='class_monitor',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='class_prefect',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='class_teacher',
        ),
        migrations.AddField(
            model_name='grade',
            name='classmonitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_monitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='classprefect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_prefect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='classteacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
