# Generated by Django 3.1.2 on 2020-10-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0004_remove_color_footer_color'),
        ('grades', '0004_auto_20201010_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='colors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.color'),
        ),
    ]
