# Generated by Django 3.1.2 on 2020-10-21 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20201020_2332'),
        ('teachers', '0001_initial'),
        ('colors', '0004_remove_color_footer_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grades', '0005_grade_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='class_monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_monitor', to='students.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='class_prefect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_prefect', to='students.student'),
        ),
        migrations.AddField(
            model_name='grade',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_teacher', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='classmonitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_monitor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='classprefect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_prefect', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='classteacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='colors.color'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
