# Generated by Django 3.1.2 on 2020-10-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201006_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_deputy_headmaster',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_grade1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_grade2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_grade3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_grade4',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_grade5',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_grade6',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_grade7',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_grade8',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_headboy',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_headgirl',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_headmaster',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_monitor',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_prefect',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_senior_teacher',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('grade1', 'grade1'), ('grade2', 'grade2'), ('grade3', 'grade3'), ('grade4', 'grade4'), ('grade5', 'grade5'), ('grade6', 'grade6'), ('grade7', 'grade7'), ('grade8', 'grade8')], max_length=50, null=True),
        ),
    ]
