# Generated by Django 3.1.2 on 2020-10-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201009_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'teacher'), ('student', 'student'), ('prefect', 'prefect'), ('monitor', 'monitor'), ('headboy', 'headboy'), ('headgirl', 'headgirl'), ('parent', 'parent'), ('admin', 'admin'), ('headmaster', 'headmaster'), ('deputy_headmaster', 'deputy_headmaster'), ('senior_teacher', 'senior_teacher')], max_length=50, null=True),
        ),
    ]
