# Generated by Django 3.1.2 on 2020-10-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
