# Generated by Django 3.1.2 on 2020-10-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20201023_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='class_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
