# Generated by Django 3.1.2 on 2020-10-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
