from . import views
from django.urls import path, include
from .views import (
    AnswerListView,
    UserAnswersListView,
    AnswerDetailView,
    AnswerUpdateView,
    AnswerCreateView,
    AnswerDeleteView,
    UserExerciseListView,
    ExerciseDetailView,
    ExerciseListView,
    ExerciseUpdateView,
    ExerciseDeleteView,
    ExerciseCreateView,
    SubjectListView,
    SubjectDetailView,
    SubjectUpdateView,
    SubjectDeleteView,
    SubjectCreateView,
    UserSubjectListView,
    TopicListView,
    TopicDetailView,
    TopicUpdateView,
    TopicDeleteView,
    TopicCreateView,
    UserTopicListView,
    LessonListView,
    LessonDetailView,
    LessonUpdateView,
    LessonDeleteView,
    LessonCreateView,
    UserLessonListView,
    TodayListView,
    TodayDetailView,
    TodayUpdateView,
    TodayDeleteView,
    TodayCreateView,
    UserTodayListView

)


urlpatterns = [
    path('subjects', SubjectListView.as_view(), name='subject-list'),
    path('subject/<int:pk>/', SubjectDetailView.as_view(), name='subject-detail'),
    path('subject/new/', SubjectCreateView.as_view(), name='subject-create'),
    path('subject/<int:pk>/update/', SubjectUpdateView.as_view(), name='subject-update'),
    path('subject/<int:pk>/delete/', SubjectDeleteView.as_view(), name='subject-delete'),
    path('user/<str:username>', UserSubjectListView.as_view(), name='user-subjects'),
    path('topics', TopicListView.as_view(), name='topic-list'),
    path('topic/<int:pk>/', TopicDetailView.as_view(), name='topic-detail'),
    path('topic/new/', TopicCreateView.as_view(), name='topic-create'),
    path('topic/<int:pk>/update/', TopicUpdateView.as_view(), name='topic-update'),
    path('topic/<int:pk>/delete/', TopicDeleteView.as_view(), name='topic-delete'),
    path('user/<str:username>', UserTopicListView.as_view(), name='user-topics'),
    path('lesson/<int:pk>/', LessonDetailView.as_view(), name='lesson-detail'),
    path('lessons', LessonListView.as_view(), name='lesson-list'),
    path('lesson/new/', LessonCreateView.as_view(), name='lesson-create'),
    path('lesson/<int:pk>/update/', LessonUpdateView.as_view(), name='lesson-update'),
    path('lesson/<int:pk>/delete/', LessonDeleteView.as_view(), name='lesson-delete'),
    path('user/<str:username>', UserLessonListView.as_view(), name='user-lessons'),
    path('exercises', ExerciseListView.as_view(), name='exercises'),
    path('exercise/<int:pk>/', ExerciseDetailView.as_view(), name='exercise-detail'),
    path('exercise/new/', ExerciseCreateView.as_view(), name='exercise-create'),
    path('exercise/<int:pk>/update/', ExerciseUpdateView.as_view(), name='exercise-update'),
    path('exercise/<int:pk>/delete/', ExerciseDeleteView.as_view(), name='exercise-delete'),
    path('user/<str:username>', UserExerciseListView.as_view(), name='user-exercises'),
    path('answers', AnswerListView.as_view(), name='answer-list'),
    path('answer/new/', AnswerCreateView.as_view(), name='answer-create'),
    path('answer/<int:pk>/', AnswerDetailView.as_view(), name='answer-detail'),
    path('answer/<int:pk>/update/', AnswerUpdateView.as_view(), name='answer-update'),
    path('answer/<int:pk>/delete/', AnswerDeleteView.as_view(), name='answer-delete'),
    path('user/<str:username>', UserAnswersListView.as_view(), name='user-answers'),
    path('<int:answer_id>', views.answer, name='answer'),
    path('todays', TodayListView.as_view(), name='today-list'),
    path('today/<int:pk>/', TodayDetailView.as_view(), name='today-detail'),
    path('today/new/', TodayCreateView.as_view(), name='today-create'),
    path('today<int:pk>/update/', TodayUpdateView.as_view(), name='today-update'),
    path('today/<int:pk>/delete/', TodayDeleteView.as_view(), name='today-delete'),
    path('user/<str:username>', UserTodayListView.as_view(), name='user-todays'),
]   