# Generated by Django 3.1.2 on 2020-10-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201017_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_footer_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='is_footer_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='is_footer_3',
            field=models.BooleanField(default=False),
        ),
    ]
