# Generated by Django 3.1.2 on 2020-10-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bg_color',
        ),
        migrations.DeleteModel(
            name='Bg_color_2',
        ),
        migrations.DeleteModel(
            name='Bg_color_3',
        ),
        migrations.DeleteModel(
            name='Hover_border_color',
        ),
        migrations.DeleteModel(
            name='Hover_color',
        ),
        migrations.DeleteModel(
            name='Hover_text_color',
        ),
    ]
