# Generated by Django 3.1.2 on 2020-10-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_color_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='footer_color',
        ),
    ]
