# Generated by Django 3.1.2 on 2020-10-17 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20201017_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='statement',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
