# Generated by Django 3.1.2 on 2020-10-17 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20201017_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_staff',
        ),
    ]
