# Generated by Django 3.1.2 on 2020-10-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_team_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_us_1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='about_us_2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='about_us_3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='aboutusimage1',
            field=models.ImageField(null=True, upload_to='About/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='about',
            name='aboutusimage2',
            field=models.ImageField(null=True, upload_to='About/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='about',
            name='aboutusimage3',
            field=models.ImageField(null=True, upload_to='About/%Y/%m/%d/'),
        ),
    ]
