# Generated by Django 3.1.2 on 2020-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_auto_20201017_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='icon1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='icon2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='icon3',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
