# Generated by Django 3.1.2 on 2020-10-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20201017_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_us_4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='about_us_5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='about_us_6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='about_us_7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='aboutusimage4',
            field=models.ImageField(null=True, upload_to='About/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='about',
            name='aboutusimage5',
            field=models.ImageField(null=True, upload_to='About/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='about',
            name='aboutusimage6',
            field=models.ImageField(null=True, upload_to='About/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='about',
            name='aboutusimage7',
            field=models.ImageField(null=True, upload_to='About/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='about',
            name='number4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='number5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='number6',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='number7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title5',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='title7',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='welcome_message',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='about_us_3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='icon1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='icon2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='icon3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title3',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
