# Generated by Django 3.1.2 on 2020-10-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0010_auto_20201017_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='parent_image',
            field=models.ImageField(null=True, upload_to='About/%Y/%m/%d/'),
        ),
    ]
