# Generated by Django 3.1.2 on 2020-10-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_about_parent_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='parent_image',
            new_name='testimonial_parent_image',
        ),
    ]
