# Generated by Django 3.1.2 on 2020-10-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20201017_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title6',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
