# Generated by Django 3.1.2 on 2020-10-18 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0014_auto_20201018_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='bottombannertitle1',
            new_name='bottombannerstatement',
        ),
    ]
