# Generated by Django 3.1.2 on 2020-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0015_auto_20201018_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bottombannerstatement4',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
