# Generated by Django 3.1.2 on 2020-10-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_about_bottombannerstatement4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='bottombannerstatement',
        ),
        migrations.RemoveField(
            model_name='about',
            name='bottombannerstatement1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='bottombannerstatement2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='bottombannerstatement3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='bottombannerstatement4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='topbannerstatement1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='topbannerstatement2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='topbannerstatement3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='topbannerstatement4',
        ),
        migrations.RemoveField(
            model_name='about',
            name='topbannertitle1',
        ),
        migrations.RemoveField(
            model_name='about',
            name='topbannertitle2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='topbannertitle3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='topbannertitle4',
        ),
    ]
