# Generated by Django 3.1.2 on 2020-10-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0020_auto_20201018_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='statement',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
