# Generated by Django 3.1.2 on 2020-10-16 12:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0001_initial'),
        ('grades', '0005_grade_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('questions', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('questions_typed', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('exercise_answers', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('answers_explanation', models.FileField(blank=True, null=True, upload_to='exercise_videos/%Y/%m/%d')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('is_grade1', models.BooleanField(default=False)),
                ('is_grade2', models.BooleanField(default=False)),
                ('is_grade3', models.BooleanField(default=False)),
                ('is_grade4', models.BooleanField(default=False)),
                ('is_grade5', models.BooleanField(default=False)),
                ('is_grade6', models.BooleanField(default=False)),
                ('is_grade7', models.BooleanField(default=False)),
                ('is_grade8', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('classname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.grade')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.CharField(max_length=100, null=True)),
                ('slug', models.SlugField(max_length=250, null=True, unique_for_date='date_posted')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='lesson_videos/%Y/%m/%d')),
                ('content', models.TextField(null=True)),
                ('lesson_pic1', models.ImageField(blank=True, null=True, upload_to='lesson_pics/%Y/%m/%d/')),
                ('lesson_pic2', models.ImageField(blank=True, null=True, upload_to='lesson_pics/%Y/%m/%d/')),
                ('lesson_pic3', models.ImageField(blank=True, null=True, upload_to='lesson_pics/%Y/%m/%d/')),
                ('lesson_pic4', models.ImageField(blank=True, null=True, upload_to='lesson_pics/%Y/%m/%d/')),
                ('lesson_pic5', models.ImageField(blank=True, null=True, upload_to='lesson_pics/%Y/%m/%d/')),
                ('lesson_pic6', models.ImageField(blank=True, null=True, upload_to='lesson_pics/%Y/%m/%d/')),
                ('lesson_pic7', models.ImageField(blank=True, null=True, upload_to='lesson_pics/%Y/%m/%d/')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_mvp', models.BooleanField(default=False, help_text='click this if this is pp1, pp2, grade_1, grade_2, grade_3')),
                ('is_grade1', models.BooleanField(default=False)),
                ('is_grade2', models.BooleanField(default=False)),
                ('is_grade3', models.BooleanField(default=False)),
                ('is_grade4', models.BooleanField(default=False)),
                ('is_grade5', models.BooleanField(default=False)),
                ('is_grade6', models.BooleanField(default=False)),
                ('is_grade7', models.BooleanField(default=False)),
                ('is_grade8', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('grade_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade')),
            ],
            options={
                'verbose_name': 'Sub_strand',
                'verbose_name_plural': 'Sub_strands',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='date_posted')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_grade1', models.BooleanField(default=False)),
                ('is_grade2', models.BooleanField(default=False)),
                ('is_grade3', models.BooleanField(default=False)),
                ('is_grade4', models.BooleanField(default=False)),
                ('is_grade5', models.BooleanField(default=False)),
                ('is_grade6', models.BooleanField(default=False)),
                ('is_grade7', models.BooleanField(default=False)),
                ('is_grade8', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('specific_grade', models.ForeignKey(blank=True, help_text='eg class 7', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='grades.grade')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subject_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learning_area',
                'verbose_name_plural': 'Learning_areas',
                'ordering': ['subject_name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('overview', ckeditor.fields.RichTextField(blank=True, help_text='input specific learning outcomes, val-ues, pcl, & core competence', null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_grade1', models.BooleanField(default=False)),
                ('is_grade2', models.BooleanField(default=False)),
                ('is_grade3', models.BooleanField(default=False)),
                ('is_grade4', models.BooleanField(default=False)),
                ('is_grade5', models.BooleanField(default=False)),
                ('is_grade6', models.BooleanField(default=False)),
                ('is_grade7', models.BooleanField(default=False)),
                ('is_grade8', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('grade_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Strand',
                'verbose_name_plural': 'Strands',
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_grade1', models.BooleanField(default=False)),
                ('is_grade2', models.BooleanField(default=False)),
                ('is_grade3', models.BooleanField(default=False)),
                ('is_grade4', models.BooleanField(default=False)),
                ('is_grade5', models.BooleanField(default=False)),
                ('is_grade6', models.BooleanField(default=False)),
                ('is_grade7', models.BooleanField(default=False)),
                ('is_grade8', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.exercise')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.lesson')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='today_teacher', to='teachers.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lesson_teacher', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.topic'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.lesson'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.topic'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers_typed', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='subjects.exercise')),
                ('yourname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_answering', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
