# Generated by Django 3.1.2 on 2020-10-16 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='yourname',
        ),
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentAnswering', to=settings.AUTH_USER_MODEL),
        ),
    ]
