# Generated by Django 3.1.2 on 2020-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_answer_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='marked',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
