# Generated by Django 3.1.2 on 2020-10-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20201016_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='marked',
            new_name='unmarked',
        ),
    ]
