# Generated by Django 3.1.2 on 2020-10-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_auto_20201016_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='today',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.exercise'),
        ),
    ]
