# Generated by Django 3.1.2 on 2020-10-24 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20201023_0805'),
        ('teachers', '0004_auto_20201023_0805'),
        ('subjects', '0009_topic_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='subject_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjectteacher', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentAnswering', to='students.student'),
        ),
    ]
