# Generated by Django 3.1.2 on 2020-10-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_auto_20201024_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='subject_teacher',
            new_name='teacher',
        ),
    ]
